version: '3'

services:
  web:
    image: yingxuan-docker.pkg.coding.net/1024/1024-docs/${REF_TAG}:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - net
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.services.app1024doc.loadbalancer.server.port=3000
        - traefik.http.routers.app1024doc.rule=Host(`doc.1024code.com`)
        - traefik.http.routers.app1024doc.tls
        - traefik.http.routers.app1024doc.tls.certresolver=myresolver
        - traefik.http.routers.app1024doc.middlewares=https_redirect

networks:
  net:
  traefik:
    external: true