name: production deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: yingxuan-docker.pkg.coding.net/1024/1024-docs/${{ github.ref_name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest
          flavor: |
            latest=auto
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: yingxuan-docker.pkg.coding.net
          username: ${{ secrets.CODING_USER }}
          password: ${{ secrets.CODING_TOKEN }}

      - name: Initialize production environment
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "service_id=56014292-216b-4177-8cfe-b8d2f595475c" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        timeout-minutes: 5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deployment
        if: ${{ env.service_id }}
        run: >-
          curl -X POST https://por.apps.1024code.com/api/webhooks/${{env.service_id}}?tag=${{steps.meta.outputs.version}}
